//
//  secondViewController.swift
//  tour
//
//  Created by Nano Degree on 10/01/2017.
//  Copyright © 2017 HCD. All rights reserved.
//

import UIKit

class secondViewController: BaseClassViewController, UICollectionViewDelegate, UICollectionViewDataSource {
    
    
    
    @IBOutlet weak var lblTitle: UILabel!
    struct ceoObject {
        
        var username: String
        var profilePicture: UIImage
        var post: String
      
        
        }
    var ceoArray: [ceoObject] = []
    
    
    
    var selectedCID : Int = 0
    
    var CityTitle : String = ""
    
    
    @IBOutlet weak var collectionview: UICollectionView!
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        
        if CityTitle == "" {
            let pre = UserDefaults.standard
            CityTitle = pre.object(forKey: "SelectedID") as! String
        }
        
        switch CityTitle
        {
            
        case "KPK":
            ceoArray.append(ceoObject(username:"CHITRAL", profilePicture: UIImage(named: "c1")!, post: "Chitral , also spelled Chetrar, translated as field, is the capital of the Chitral District, situated on the western bank of the Chitral River (also called Kunar River), in Khyber Pakhtunkhwa, Pakistan. It also served as the capital of the princely state of Chitral until 1969. The town is at the foot of Tirich Mir, the highest peak of the Hindu Kush, which is 25,289 ft (7,708 m) high. It has a population of 20,000. The elevation of the valley is 3,700 ft (1,100 m).") )
            ceoArray.append(ceoObject(username: "MALAM JABBA",profilePicture: UIImage(named: "ma1")!, post: "Malam Jabba is a Hill Station in the Hindu Kush mountain range nearly 40 km from Saidu Sharif in Swat Valley, Khyber Pakhtunkhwa, Pakistan. It is 314 km from Islamabad and 51 km from Saidu Sharif Airport.Malam Jabba is home to the only ski resort in Pakistan. The area also contains two Buddhist stupas and six monasteries that are scattered around the resort. The presence of the monuments at such a height indicates that the area has been inhabited for over 2000 years.") )
            ceoArray.append(ceoObject(username: "DAMAN-E-KOH",profilePicture: UIImage(named: "mar1")!, post: "The Margalla Hills is a hill range part of the foothills Himalayas located within the Margalla Hills National Park, north of Islamabad, Pakistan. Margalla Range has an area of 12,605 hectares. The hills are a part of Murree hills. It is a range with many valleys as well as high mountains. It is part of the Margalla Hills National Park.The hill range nestles between an elevation of 685 meters at the western end and 1,604 meters on its east with average height of 1000 meters. Its highest peak is Tilla Charouni. The range gets snowfall in winters. On 6 January 2012, after almost six years, Pir Sohawa, the cityís highest tourist spot, received few inches of snowfall. Another measurable snow event occurred on 11 February 2016 where 2 inches fell after four years.") )
    ceoArray.append(ceoObject(username: "SAIF-UL-MALOOK",profilePicture: UIImage(named: "s1")!, post: "Saiful Muluk is a mountainous lake located at the northern end of the Kaghan Valley, near the town of Naran.It is in the north east of Mansehra District in the Khyber-Pakhtunkhwa province, Pakistan and feeds water to Kunhar river. At an elevation of 3,224 m (10,578 feet) above sea level, it is well above the tree line, and is one of the highest lakes in Pakistan.") )
            ceoArray.append(ceoObject(username: "ANSO LAKE",profilePicture: UIImage(named: "Ansoo Lake")!, post: "Ansoo Lake is situated in Manoor Valley, Kaghan Valley in the Mansehra District of the Khyber-Pakhtunkhwa province of Pakistan. It is located near Malika Parbat in the Himalayan range at the altitude of 5,027 meters (16,493 ft). This lake is considered to be one of the most beautiful lakes of the world. The name Ansoo comes from its tear-like shape (the Urdu word Ansoo means teardrop). The lake also resembles a human eye with a central ice island resembling the iris and a ridge resembling an eyebrow, which becomes even more prominent when ice melts on the eyebrow during the summer. This ridge was partially destroyed in the 2005 Kashmir earthquake. The lake is said to have been discovered in 1993 by Pakistan Air Force pilots who were flying low in the area. Earlier, the lake was not even known to the locals. There is no place to stay at Ansoo Lake. Some people may camp on the top of extremely cold and windy mountains but it is very risky and even the locals do not recommend this.") )
                ceoArray.append(ceoObject(username: "AYUBIA",profilePicture: UIImage(named: "Ayubia")!, post: "Ayubia National Park, also known as Ayubia, is a protected area of 3,312 hectares (8,184 acres)[1] located in Abbottabad District, Khyber Pakhtunkhwa province, Pakistan. It was declared a national park in 1984. Ayubia was named after Muhammad Ayub Khan, second President of Pakistan. The area supports temperate coniferous forest and temperate broadleaf and mixed forest ecoregion habitats, with an average elevation of 8,000 feet (2,400 m) above the sea level.") )
            ceoArray.append(ceoObject(username: "BABUSAR TOP",profilePicture: UIImage(named: "BabsarTop")!, post: "Babusar Pass or Babusar Top(el. 4173 m./13,691 ft.) is a mountain pass at the north of the 150 km. (93 miles) long Kaghan Valley connecting it via the Thak Nala with Chilas on the Karakoram Highway (KKH). It is the highest point in the Kaghan Valley that can be easily accessed by cars. Babusar Pass connects Gilgit Baltistan with Khyber Pakhtunkhwa province of Pakistan.") )
            ceoArray.append(ceoObject(username: "NARAN",profilePicture: UIImage(named: "naran")!, post: "Naran is a medium sized town in upper Kaghan Valley in Mansehra District of Khyber Pakhtunkhwa province of the Pakistan. It is located 119 kilometers (74 mi) from Mansehra city at the altitude of 8,202 feet (2,500 m). Naran is one of the most scenic towns in Pakistan, attracting thousands of tourists, trekkers, photographers and nature-enthusiast, every year. The Kunhar River, swollen by glacial melt, passes through this town as it meanders its way through the valley.Kunhar river in Naran during the month of June as viewed from PTDC motel Naran can be considered as base station to scenic destinations like Lake Saif-ul-Malook, Lalazar Babusar, Noori Valley and Purbi Valley.") )
            ceoArray.append(ceoObject(username: "KAGHAN",profilePicture: UIImage(named: "Kaghan")!, post: "Kaghan Valley is an alpine-climate valley in Mansehra District of the Khyber Pakhtunkhwa Province of Pakistan. Landslides caused by the devastating 2005 Kashmir earthquake closed the Kaghan Valley road and cut off the valley from the outside. The road now has been rebuilt.The valley extends 155 kilometers (96 mi), rising from an elevation of 2,134 feet (650 m) to its highest point, the Babusar Pass, at 13,690 feet (4,170 m)") )
            ceoArray.append(ceoObject(username: "SIRI PAYE",profilePicture: UIImage(named: "siri paye")!, post: "Siri Paye Meadows is one of the most beautiful and picturesque places in Northern Pakistan where nature can be found blushing everywhere. In spring season, the flowers bloom and these colorful creatures look awe-inspiring with the white backdrop of the Makra Peak. This place is simply the best for a weekend adventure or even a full-fledge tour away from your stressful routine. This small hamlet provides the excursion which simply makes your day full of joy and excitement. Visiting the place in the summer months allows one to experience the fresh and cool weather amidst the friendly local people. The splendor and the charm of this place will remain embedded in your memory for long. You will simply find yourself in another world as soon as you will get into this enchanting and vibrant hideout that features bountiful thrills and fabulous treks to the visitors. There is a lot to explore about this beautiful haven of Pakistan and words wonít be enough to express the real beauty of this marvel of nature.") )
            ceoArray.append(ceoObject(username: "MAKRA PEAK",profilePicture: UIImage(named: "makra peak")!, post: "The Makra is a scenic peak in the Mansehra District in Hazara Region of the Himalayas in northern Pakistan. It is 4,000 metres (13,123 ft) high and almost 200 km from Islamabad on the Naran Road. From Kiwai, a single 7-kilometre-long road runs uphill to Shogran, a tourist resort with numerous hotels; the track continues to climb up to Seree Lake and ends at Paye. From here it is a trek of four hours to the top of the Makra. Hiking on the Makra is difficult due to snow and the gradient of the mountainsides.Although it can be straightforward to climb, fatalities have occurred during storms and the fatality rate is 30%. In spite of its difficulties, the summit offers the good views of Hazara and Azad Kashmir. Fatalities tend to occur in bad weather, especially thick fog, and as a result of the steepness of some sections. The waters from the mountain's glacier feed the Kunhar River.") )
            ceoArray.append(ceoObject(username: "SHOGRAN",profilePicture: UIImage(named: "shogran")!, post: "Shogran (Urdu: ?????? ?) is a hill station situated on a green plateau in the Kaghan Valley, northern Pakistan at a height of 7,749 feet or 2,362 metres above sea level. Shogran is located at a distance of 34 km away from Balakot. The road from Islamabad to Kiwai is metalled and measures 212 km. From Shogran, you can ride a jeep or horse or hike to several picturesque places like Siri, Paye and Makra Peak. Hotels and motels are available at affordable costs. Mobile phone services is also available there by Telenor and Mobilink. The local people are friendly and peaceful. It is accessible in the summer. It attracts families and explorers alike. You should not miss a trip to Forest Rest House. Most of the people sit and relax in its huge lush green lawns. Entry might be restricted when senior officials visit or stay at rest houses. Views of Sri Paya and Musa Da Mussalah Peak are really nice from the lawns of the rest house.") )
            ceoArray.append(ceoObject(username: "BAHRAIN",profilePicture: UIImage(named: "bahrain")!, post: "Bahrain is a hill station located in Swat District of Khyber Pakhtunkhwa, Pakistan, 60 km North of Mingora at an elevation of 4700 ft on the right bank of Swat river. It is named Bahrain (lit. two rivers) due to its location at the confluence of the Daral and Swat rivers. It is known for its riverside tourist resorts, local handicrafts, and its view of the merging of the Daral and Swat Rivers. It also serves as a base camp for the trail that leads to the Daral & Saidgai lakes.") )
            ceoArray.append(ceoObject(username: "WHITE PALACE",profilePicture: UIImage(named: "white palace")!, post: "The White Palace of Marghazar was built in 1940 by the first king of Swat, Miangul Abdul Wadud (Badshah Sahib) in the small town of Marghazar situated at about 13 kilometers away from Saidu Sharif. The name was given to the palace as it was built of white marble. The palace now serves as a hotel. The White Palace at Marghazar was the summer residence of the Wali of Swat, Miangul Jehanzeb. Located at 7,000 feet above sea level on Marghazar Hill, it was later converted into a tourist resort.") )
            ceoArray.append(ceoObject(username: "DUDIPATSAR LAKE",profilePicture: UIImage(named: "dudipatsar lake")!, post: "Dudipatsar Lake or Dudipat Lake is a lake encircled by snow clad peaks in Lulusar-Dudipatsar National Park. The lake lies in the extreme north of the Kaghan Valley, in the Mansehra District, Khyber Pakhtunkhwa province, in northern Pakistan. The word dudi means white, pat means mountains and sar means lake. This name has been given to the lake because of the white color of snow at surrounding peaks. In summer the water of the lake reflects like a mirror. The word sar is used with the name of each lake in the area, translating as 'lake") )
            ceoArray.append(ceoObject(username: "KALAM",profilePicture: UIImage(named: "kalam")!, post: "Kalam is a cool heaven for tourists which is located at distance of 99 km from Mingora in the northern upper reaches of Swat valley along the bank of Swat River in Khyber Pakhtunkhwa province of Pakistan. Kalam is surrounded by lush green hills, thick forests and bestowed with mesmeric lakes, meadows and waterfalls which are worth seen features of the landscape. It is the birthplace of Swat river which forms with confluence of two major tributaries of Gabral river & Ushu river.") )
            ceoArray.append(ceoObject(username: "KIWAI",profilePicture: UIImage(named: "kiwai")!, post: "There is a very cool restaurant in Kiwai with the name of Aabshar Cafe. it has seats and tables placed in the Abshar.") )
            ceoArray.append(ceoObject(username: "LALAZAR",profilePicture: UIImage(named: "lalazar")!, post: "Lalazar is a tourist spot situated 21 km from Naran in Kaghan Valley, Pakistan. It is located at the height of 10,499 feet (3,200 meters). Lalazar is a lush green meadow with full of wild flowers and pine and fir forest. The road to Lalazar is a typical Pakistani mountain road, with hills on one side and a deep khud (valley) on the other side. The only difference was that the khud is the Kunhar River. Lalazar is a place where one would enjoy camping. It is a must-see when visiting the Kaghan Valley and attracts lots of visitors every year. Its great beauty is highly appreciated, and people go to see its beautiful wildlife. It is also a full day trip like Saiful Maluk. On a clear sunny day, its possible to view the snow-covered peak of Falak Sonia from Lalazar. This peak has also got a fairy tale story in its background, like most of the other places in Kaghan Valley. You may also see the River Kunhar flowing roughly thousands of miles below the altitude you would be standing. It is accessible by a jeep track from Naran via Battakundi. Lalazar is situated on the other end of Lake Saiful Muluk, over the mountain; a small resort worth visiting. A large green plateau gives a lovely view of the valley below. The place can be reached through the deadliest track on jeep with several twists and turn. For hiker lovers, there is another track, a 5-hour hike, over a mountain pass from Lake Saiful Muluk. You may find a guide. One can get a chance to see the rare wildlife variety of Markhoor on this track during the months of October and November") )
            ceoArray.append(ceoObject(username: "LULUSAR LAKE",profilePicture: UIImage(named: "Lulusar Lake")!, post: "Lulusar is group of mountain peaks and a lake in the Kaghan Valley in the Khyber-Pakhtunkhwa province of Pakistan. The word sar means top or peak in Pashto. The highest peak has a height of 11,200 ft (3,410 m) above sea level (N35.0804 E73.9266). The locale is famous for the scenic and large Lulusar Lake, which is a popular tourism attraction.") )
            ceoArray.append(ceoObject(username: "MAHUDAND LAKE",profilePicture: UIImage(named: "mahudand lake")!, post: "Mahudand Lake (Lake of Fishes) is a lake located in the upper Usho Valley at a distance of about 40 km from Kalam, Swat District, Khyber Pakhtunkhwa province of Pakistan. The lake is accessible by a four-wheel drive vehicle, and is often utilized for fishing and boating.") )
            ceoArray.append(ceoObject(username: "MALIKA PARBAT",profilePicture: UIImage(named: "malika parbat")!, post: "Malika Parbat (Queen of the mountains) (el. 5,290 metres (17,356 ft)) is the highest peak in Kaghan Valley, Khyber Pakhtunkhwa, Pakistan about six km south of Lake Saiful Muluk near Ansoo Lake.The mountain is clearly visible from the popular tourist spot of Lake Saiful Maluk in Kaghan Valley. Malika Parbat is accessible from Naran-Lake Saiful Muluk side and from Batakundi-Dadar Chitta Glacier. There are three summits that forms Malika Parbat, Malika Parbat (North Peak), Malika Parbat Cresta, and Malika Parbat (South Peak).") )
            ceoArray.append(ceoObject(username: "NATHIA GALI",profilePicture: UIImage(named: "Nathiagali")!, post: "Nathia Gali or Nathiagali (Pashto: ????? ????, Urdu: ????? ????) is a mountain resort town or hill station in Abbottabad District of Khyber Pakhtunkhwa, Pakistan. It is a part of the Galyat range, where several hill-stations are situated, closely connected to each other, and with their names mostly ending in 'Gali'. Nathiagali is known for its scenic beauty, hiking tracks and pleasant weather, which is much cooler than the rest of the Galyat due to it being at a greater altitude. It is situated 34 kilometers at one hour's drive away from both Murree and Abbottabad, lying midway between these two places. The drive time from Islamabad is usually about two hours, unless there is a lot of traffic") )
            ceoArray.append(ceoObject(username: "SAJIKOT WATERFALL",profilePicture: UIImage(named: "Sajikot Water Fall")!, post: "It is roughly 1-1.5KM ahead of Sajjikot bazaar on the same road. When you cross Sajjikot you cross a Nala. The waterfall is visible from the road or at least audible from the road. Also note that it is a 3 step waterfall. The first two are small steps and the last one and the most famous one is huge. But the upper two steps are also beautiful. If you want to visit them then you should descend just before the main waterfall.") )
            
            break;
            
case "SINDH":
    ceoArray.append(ceoObject(username:"KARACHI", profilePicture: UIImage(named: "k3")!, post: "Karachi is the largest and most populous city in Pakistan and 5th largest metropolitan city in the world. Karachi is the capital of Sindh province. Ranked as a beta world city, the city is Pakistan's premier industrial and financial centre. Karachi is also Pakistan's most cosmopolitan city. Situated on the Arabian Sea, Karachi serves as a transport hub, and is home to two of Pakistan's two largest seaports, the Port of Karachi and Port Bin Qasim, as well as the busiest airport in Pakistan. Though the Karachi region has been inhabited for millennia, the city was founded as a village named Kolachi that was established as a fortified settlement in 1729. The settlement drastically increased in importance with the arrival of British colonialists who embarked on a major works to transform the city into a major seaport, and established connections to the extensive British Indian railway network. By the time of the Partition of British India, the city was the largest in Sindh with an estimated population of 400,000. Immediately following independence of Pakistan, the city's population increased dramatically with the arrival of hundreds of thousands of Muslim refugees from India.") )
    ceoArray.append(ceoObject(username: "HYDERABAD",profilePicture: UIImage(named: "h3")!, post: "Hyderabad is a city built on three hillocks cascading over each other. Mian Ghulam Shah Kalhoro of the Kalhora Dynasty founded the city in 1768 over the ruins of Neroon Kot (Nerun or Nerun Kot meaning the place of Neroon), a small fishing village on the banks of Indus River named after its ruler Neroon. A formal concept for the city was laid out by his son, Sarfraz Khan in 1782. When the foundations were laid, the city obtained the nickname Heart of the Mehran as the ruler Mian Ghulam Shah himself was said to have fallen in love with the city. In 1768 he ordered a fort to be built on one of the three hills of Hyderabad to house and defend his people. The fort was built using fire-baked bricks, on account of which it was named Pacco Qillo meaning the strong fort.") )
    ceoArray.append(ceoObject(username: "THATTA",profilePicture: UIImage(named: "t2")!, post: "Thatta Sindhi is a city and capital of Thatta District. It will be capital of the announced Banbhore Division. It is a historic town of 220,000 inhabitants in the Sindh province of Pakistan, near Lake Keenjhar, the largest freshwater lake in the country. Thatta's major monument, the necropolis at Makli Hill, is listed among the World Heritage Sites. The Shah Jahan Mosque, Thatta is mentioned separately on the tentative list since 1993. Located 100 km (62 mi) east of the provincial capital of Sindh, Karachi, it makes for a practical escape for people from the city seeking to visit the picturesque old town.") )
    ceoArray.append(ceoObject(username: "GORAK HILLS",profilePicture: UIImage(named: "gorakh hills")!, post: "Gorakh (Sindhi: گورک‎), (Urdu: گورکھ‎) is a Hill Station of Sindh, Pakistan.[1] It is situated at an elevation of 5,689 ft (1,734 m) in the Kirthar Mountains, 94 kilometres (58 mi) northwest of Dadu city. Different opinions have been given about the history and origin of the hill station. It is said that the great medieval saint, Sri Gorakhnath Ji, had extensively wandered in hills and the region. According to Nandu, an authority on Sanskrit, Gorakh is a Sanskrit word which means shepherding of sheep, cow and goat, etc. This relates to herding in particularly difficult terrain and intricate pastures which makes practical sense, because, local tribesmen do take their flocks to Gorakh Hill for summer grazing.") )
    
    break;
            
        case "PUNJAB":
            ceoArray.append(ceoObject(username:"BADSHAHI MOSQUE", profilePicture: UIImage(named: "b1")!, post: "Badshahi Mosque (transformation in English: Royal Mosque) is the second largest mosque of Pakistan, located in provincial capital Lahore of Punjab. It was built in 1673 A.D. by the sixth Mughal Emperor Aurangzeb Alamgir. The mosque remained the largest mosque of the world from 1673 to 1986, when it was overtaken in capacity and size upon the completion of Shah Faisal Mosque in Islamabad. It has a total area of 29,867.2 square meters (321, 488 square feet) and can accommodate upto 100,000 worshipers. Now it is 8th largest mosque in the world in terms of its capacity for accommodating worshipers and 10th largest in terms of total area. Badshahi Mosque with its beautiful Mughal architectural style and historical background is a major landmark and tourist attraction not only in Lahore but in whole Punjble of the Emperorís court. Shalimar name meaning is still an unresolved mystery as the historians are yet to confirm that whether it came from Arabic or the Persian origin. The place is located close to Baghbanpura on the GT road which is in the northeast direction at a distance of 5KM from the city center of Lahore.") )
            ceoArray.append(ceoObject(username: "MINAR-E-PAKISTAN",profilePicture: UIImage(named: "mi1")!, post: "Minar-e-Pakistan (Urdu: ?????? ???????? / ALA-LC: Minar-i Pakistan, literally Tower of Pakistan) is a public monument located in Iqbal Park which is one of the largest urban parks in Lahore, Punjab, Pakistan.[1] The tower was constructed during the 1960s on the site where, on 23 March 1940, the All-India Muslim League at the time of British colonial rule over British India passed the Lahore Resolution, the first official call for a separate homeland for the Muslims living in South Asia, in accordance with the two-nation theory.") )
            ceoArray.append(ceoObject(username: "MUREE",profilePicture: UIImage(named: "mu1")!, post: "Murree is a colonial era town located on the Pir Panjal Range within the Murree Tehsil, Rawalpindi District in Punjab, Pakistan. It forms outskirt of Islamabad Rawalpindi metropolitan area, and is about 30 km northeast of Islamabad City. It has average altitude of 2,291 metres Murree was founded in 1851 as a sanatorium for British troops. The permanent town of Murree was constructed in 1853 and the church was sanctified shortly thereafter. One main road was established, commonly referred to even in modern times, as the mall. Murree was the summer headquarters of the colonial Punjab Government until 1876 when it was moved to Shimla.Murree became a popular tourist station for British within the British India, several prominent Englishmen were born here including Bruce Bairnsfather, Francis Younghusband and Reginald Dyer. During colonial era acsses to commercial establishments was restricted for non-Europeans including the Lawrence College. In 1901, the population of the town was officially 1,844, although if summer visitors had been included this could have been as high as 10,000.") )
            ceoArray.append(ceoObject(username: "WAGAH BORDER",profilePicture: UIImage(named: "w1")!, post: "Wagah is a village situated in Lahore District, Punjab, Pakistan and serves as a goods transit terminal and a railway station between Pakistan and India,[1] and lies on the old Grand Trunk Road between Lahore, Punjab, Pakistan and Amritsar, India. The border is located 24 kilometres (15 mi) from Lahore and 32 kilometres (20 mi) from Amritsar. It is also 3 kilometres (1.9 mi) from the bordering village of Attari.") )
            ceoArray.append(ceoObject(username:"PATRIATA", profilePicture: UIImage(named: "Patriata")!, post: "Patriata is located in Murree Tehsil which is a subdivision of Rawalpindi District.It is the highest point in the area and the hills stand 7500 feet above sea level.") )
            break;
            
        case "BALOCHISTAN":
            ceoArray.append(ceoObject(username:"GAWADER", profilePicture: UIImage(named: "g1")!, post: "Gwadar is a port city on the southwestern coast of Balochistan, Pakistan. The city is located on the shores of the Arabian Sea, approximately 700 kilometres to the west of Pakistan's largest city, Karachi. Gwadar is near the border with Iran, and is located to the east of the Persian Gulf and opposite Oman.Gwadar and its surrounding region were overseas possessions of the Sultanate of Muscat and Oman from 1783 until Pakistan purchased the territory September 8, 1958. Pakistan assumed control of the territory on December 8, 1958, and the territory was later integrated into Balochistan province on July 1, 1977, as Gwadar District.") )
            ceoArray.append(ceoObject(username: "HANNA LAKE",profilePicture: UIImage(named: "h1")!, post: "Hanna Lake one of the beautiful Lake nestles in the hills located a little short of the place where the Urak Valley begins ten kilometers in east of Quetta city.The reservoir was constructed during the British Colonial era on the land of local tribesmen in the year 1894, and is one of the main attractions in the city and a great historical bridge wall between two mountains the depths like battlements of a fort for storing of water. The hana lake another beautiful lake is also there in Kashmir, near Banjosa, Rawalakot") )
            ceoArray.append(ceoObject(username: "QUETTA",profilePicture: UIImage(named: "q1")!, post: "Quetta  is the provincial capital of Balochistan, Pakistan and the ninth-largest city of Pakistan. The city is known as the fruit garden of Pakistan, due to the numerous fruit orchards in and around it, and the large variety of fruits and dry fruits produced there.The city was also known as Little Paris in the past because of its beauty and geographical location.The immediate area has long been one of pastures and mountains, with varied plants and animals relative to the dry plains to the west. Quetta is at an average elevation of 1,680 meters above sea level, making it Pakistan's only high-altitude major city. The population of the city is estimated to be approximately 1,140,000 Located in north western Balochistan near the Pakistan-Afghanistan border, Quetta is a trade and communication centre between the two countries. The city lies on the Bolan Pass route which was once the only gateway from Central Asia to South Asia. Quetta played an important role militarily for the Pakistani Armed Forces in the intermittent Afghanistan conflict") )
            ceoArray.append(ceoObject(username: "ZIARAT",profilePicture: UIImage(named: "z1")!, post: "Ziarat is a district in the north of Balochistan province of Pakistan. Ziarat town (situated at an altitude of about 2,400 meters) is headquarters of the district of the Sub division, and also of the tehsil. Khalifat Hills are the highest peak with an altitude of 11.400 feet in Ziarat district.") )
            ceoArray.append(ceoObject(username:"ASTOLA ISLAND", profilePicture: UIImage(named: "Astola island")!, post: "Astola Island, also known as Jezira Haft Talar Satadip or 'Island of the Seven Hills', is a small uninhabited Pakistani island in the Arabian Sea approximately 25 km (16 mi) south of the nearest part of the coast and 39 km (24 mi) southeast of the fishing port of Pasni. Astola is Pakistan's largest offshore island at approximately 6.7 km (4.2 mi) long with a maximum width of 2.3 km (1.4 mi) and an area of approximately 6.7 km2 (2.6 sq mi). The highest point is 246 ft (75 m) above sea level. Administratively, the island is part of the Pasni subdistrict of Gwadar District in Balochistan province. The island can be accessed by motorized boats from Pasni, with a journey time of about 5 hours to reach the island.") )

            ceoArray.append(ceoObject(username:"KUND MALEER", profilePicture: UIImage(named: "kund maleer")!, post: "Kund Malir is a beach in Balochistan, Pakistan located in Hingol National Park, about 145 km from Zero-Point on Makran Coastal Highway. The drive between Kund Malir and Ormara is considered to be scenic. The area is part of Hingol National Park which is the largest in Pakistan. Travelling time from Karachi is around 4 hours and there are no food and fuel facilities available on the way after Zero-Point. It is considered to be one of the most beautiful beaches in this world. However lacking the basic facilities like hotels, restaurants, fuel stations and no cell phone signals it still is worth visiting with a really calm peaceful and soothing environment.") )

            ceoArray.append(ceoObject(username:"MOOLA CHOTOK", profilePicture: UIImage(named: "moola chotok")!, post: "Valley of Moola occupies a significant geographical status due its strategic importance and central location. It has always been the suitable passage in ancient times to link India to Afghanistan and Central Asia. Owing to the fact not only the local nomads usually going to Sindh from Balochistan (famous as Sindh khurasaan) in winter season for earning of livelihood sources, but also the renowned Army Generals, Invaders, Kings, ambassadors etc opted Moola pass for example Caractrus, one of the famous General of Alexander the Great in B.C, Mohammad Bin Qasim,s Army troops, Mir Noori Naseer khan while attacking Dehli ,Famous Mughul ambassador and general Ameer Mohammad Maasum Shah built a monument at Village pir lakka Moola . The valley is an integral part of the strategic and Defence It used to be the most suitable route in ancient times when mettled roads and vehicles were not available. The importance of the pass is so because its scenic beauty would fascinate and attract the travelers and presence of population there would contribute in deciding to opt the track. Moreover, the Valley would be safest track due its strategic composition as there is a penalty of water flowing annually in the Moola River bed and the variety of different mountain rages which matter in Defense factor. The historical and cultural remains of the area provide evidence about human activities covering a large span of time.") )

            break;
            
        case "GILGIT/BALTISTAN":
            ceoArray.append(ceoObject(username:"DEOSAI", profilePicture: UIImage(named: "d1")!, post: "The Deosai National Park is located in between Skardu, Gultari, Kharmang and Astore Valley, in the Gilgit-Baltistan region of Pakistan, the majority of which falls in Skardu district.") )
            ceoArray.append(ceoObject(username: "FAIRY MEADOWS",profilePicture: UIImage(named: "f1")!, post: "Fairy Meadows, named by German climbers and locally known as Joot, is a grassland near one of the base camp sites of the Nanga Parbat, located in Diamer District, Gilgit-Baltistan.At an altitude of about 3,300 meters above the sea level, it serves as the launching point for trekkers summiting on the Rakhiot face of the Nanga Parbat.In 1995, the Government of Pakistan declared Fairy Meadows a National Park.") )
            ceoArray.append(ceoObject(username: "HUNZA",profilePicture: UIImage(named: "hu")!, post: "Hunza was formerly a princely state bordering Uyghurstan also called Xinjiang to the northeast and Pamir to the northwest, which survived until 1974, when it was finally dissolved by Zulfikar Ali Bhutto. The state bordered the Gilgit Agency to the south and the former princely state of Nagar to the east. The state capital was the town of Baltit (also known as Karimabad); another old settlement is Ganish Village. Hunza was an independent principality for more than 900 years. The British gained control of Hunza and the neighbouring valley of Nagar between 1889 and 1892 through a military conquest. The then Mir/Tham (ruler) Mir Safdar Ali Khan of Hunza fled to Kashghar in China and sought what would now be called political asylum.") )
            ceoArray.append(ceoObject(username: "K2",profilePicture: UIImage(named: "k2")!, post: "K2, also known as Mount Godwin-Austen or Chhogori is the second highest mountain in the world, after Mount Everest, at 8,611 metres above sea level. It is located on the China-Pakistan border between Baltistan, in the GilgitñBaltistan region of northern Pakistan, and the Taxkorgan Tajik Autonomous County of Xinjiang, China.K2 is the highest point of the Karakoram range and the highest point in both Pakistan and Xinjiang.K2 is known as the Savage Mountain due to the extreme difficulty of ascent. It has the second-highest fatality rate among the eight thousanders. With around 300 successful summits and 77 fatalities, about one person dies on the mountain for every four who summit. It is more difficult and hazardous to reach the peak of K2 from the Chinese side; thus, it is usually climbed from the Pakistani side. Unlike Annapurna, the mountain with the highest fatality-to-summit rate, or the other eight thousanders, K2 has never been climbed during winter.") )
            ceoArray.append(ceoObject(username:"ALTIT FORT", profilePicture: UIImage(named: "altit fort")!, post: "Altit Fort is an ancient fort at Altit town in the Hunza valley in Gilgit Baltistan, Pakistan. It was originally home to the hereditary rulers of the Hunza state who carried the title Mir, although they moved to the somewhat younger Baltit fort nearby three centuries later. Altit Fort and in particular the Shikari tower is around 1100 years old, which makes it the oldest monument in the GilgitñBaltistan.") )
            ceoArray.append(ceoObject(username:"BALTIT FORT", profilePicture: UIImage(named: "Baltit Fort")!, post: "Baltit Fort is an ancient fort in the Hunza valley in Gilgit-Baltistan, Pakistan. Founded in the 1st CE, it has been on the UNESCO World Heritage Tentative list since 2004. In the past, the survival of the feudal regime of Hunza was ensured by the impressive fort, which overlooks Karimabad. The foundations of the fort date back to 700 years ago, with rebuilds and alterations over the centuries. In the 16th century the local prince married a princess from Baltistan who brought master Balti craftsmen to renovate the building as part of her dowry. The Mirs of Hunza abandoned the fort in 1945, and moved to a new palace down the hill. The fort started to decay which caused concern that it might possibly fall into ruin. Following a survey by the Royal Geographical Society of London a restoration programme was initiated and supported by the Aga Khan Trust for Culture Historic Cities Support Programme. The programme was completed in 1996 and the fort is now a museum run by the Baltit Heritage Trust.") )
            ceoArray.append(ceoObject(username:"ATTABAD LAKE", profilePicture: UIImage(named: "attabad lake")!, post: "Attabad Lake, Hunza Valley, also known as Attabad Lake[4], is a lake in Ganish (Central Hunza Valley of northern Pakistan) created in January 2010 by a landslide dam. Since the lake was formed the only means of crossing was by loading vehicles onto wooden boats. This changed when a road tunnel was built and it opened for traffic in September 2015. The lake was formed due to a massive landslide at Attabad village in Gilgit-Baltistan, 9 miles (14 km) upstream (east) of Karimabad that occurred on 4 January 2010.[5] The landslide killed twenty people and blocked the flow of the Hunza River for five months. The lake flooding has displaced 6,000 people from upstream villages, stranded (from land transportation routes) a further 25,000,[6] and inundated over 12 miles (19 km) of the Karakoram Highway.[2] The lake reached 13 miles (21 km) long and over 100 metres (330 ft) in depth by the first week of June 2010 when it began flowing over the landslide dam, completely submerging lower Shishkat and partly flooding Gulmit.[2] The subdivision of Gojal has the greatest number of flooded buildings, over 170 houses, and 120 shops. The residents also had shortages of food and other items due to the blockage of the Karakoram Highway.[7][8] By 4 June water outflow from the lake had increased to 3,700 cu ft/s (100 m3/s).Water levels continued to rise in 18 June 2010 caused by a difference in the outflow and inflow of the new lake. As bad weather continued, the supply of food, medicine and other goods was stopped as all forms of transportation including helicopter service to Hunza could not resume.") )
            ceoArray.append(ceoObject(username:"KHAPLU FORT", profilePicture: UIImage(named: "khaplu fort")!, post: "Khaplu Palace locally known as Yabgo Khar, is an old fort and palace located in Khaplu, in the Baltistan region of Gilgit-Baltistan Province in Northern Pakistan. The palace, considered an architectural heritage and a tourist attraction, was built in the mid-19th century, replacing an earlier fort located nearby. It served as a royal residence for the Raja of Khaplu. From 2005 to 2011 the palace, having earlier stood in vulnerable conditions, underwent a restoration project carried out by the Aga Khan Trust for Culture under the Aga Khan Historic Cities Programme. The palace now houses a hotel operated by Serena and a museum depicting the history and culture of Baltistan.") )
            ceoArray.append(ceoObject(username:"KHUNJERAB PASS", profilePicture: UIImage(named: "khunjerab pass")!, post: "Khunjerab Pass or Khunjerav (elevation 4,693 metres or 15,397 feet) is a high mountain pass in the Karakoram Mountains in a strategic position on the northern border of Pakistan's GilgitñBaltistan Hunza ñ Nagar District on the southwest border of the Xinjiang region of China. Its name is derived from two words of the local Wakhi language : Khun means Home and Jerav means a creek coming from spring water/water falling.") )
            ceoArray.append(ceoObject(username:"MANTHOKA WATERFALL", profilePicture: UIImage(named: "manthoka waterfall")!, post: "Manthokha Waterfall is a water fall located in Kharmang valley, Skardu,baltistan.[1] This waterfall is approx 180 feet high from ground and located 40 km away from main Skradu town.") )
            ceoArray.append(ceoObject(username:"NALTAR", profilePicture: UIImage(named: "naltar")!, post: "Naltar is a valley near Gilgit, Hunza and Nomal, Gilgit Baltistan in the GilgitñBaltistan province of Pakistan. Naltar is 40 km (25 mi) from Gilgit and can be reached by jeeps. Naltar is a forested (pine) village known for its wildlife and magnificent mountain scenery. Now the communication is available by the efforts of Pakistan army signal corps (SCO special communication organization). There are ski lifts under the 'Ski Federation of Pakistan'. Transport is available from Gilgit to Naltar but during a specific time after that own arrangement.Mountains of Naltar, on the foothills of which, Skiing is a popular sport. Ski competitions are held at Naltar under the supervision of PAF. Naltar Bala and Naltar Pine are two villages of Naltar valley. N.Pine Is at a distance of 34 kilometers (21 mi) and Naltar Bala at 40 kilometers (25 mi) from Gilgit. There is a main village known as Nomal between Naltar valley and Gilgit. A road from Nomal goes to The Silk Route to China.") )
            ceoArray.append(ceoObject(username:"NANGA PARBAT", profilePicture: UIImage(named: "Nanga Parbat")!, post: "Nanga Parbat (Naked Mountain) is the ninth highest mountain in the world at 8,126 metres (26,660 ft) above sea level. It is the western anchor of the Himalayas around which the Indus river skirts into the plains of Pakistan. It is located in the Gilgit-Baltistan region of Pakistan and is locally known as Deo Mir (Deo meaning huge) (mir meaning mountain). Nanga Parbat is one of the eight-thousanders, with a summit elevation of 8,126 metres (26,660 ft). An immense, dramatic peak rising far above its surrounding terrain, Nanga Parbat is also a notoriously difficult climb. Numerous mountaineering deaths in the mid and early 20th century lent it the nickname killer mountain.") )
            ceoArray.append(ceoObject(username:"PASSU CONES", profilePicture: UIImage(named: "passu cones")!, post: "Passu is a small village on the Karakoram Highway, beside the Hunza River, some 15 kilometers from Gulmit, the Tehsil headquarters of Gojal in the Gilgit-Baltistan region of Pakistan, and about 150 km upriver from Gilgit. It lies very near the tongue of the Passu Glacier, and just south of the tongue of the Batura Glacier. The latter is the seventh longest non-polar glacier in the world at 56 km, and reaches very near to the highway. The people are Wakhi and speak the Wakhi Language. Religiously they are Ismaili, a sect of Shia Islam.Tupopdan, 6,106 metres (20,033 ft), also known as Passu Cones or Passu Cathedral, lies to the north of the village.") )
            ceoArray.append(ceoObject(username:"RAMA LAKE", profilePicture: UIImage(named: "rama lake")!, post: "Rama Lake is a lake near Astore in Gilgit-Baltistan, Pakistan. It is on the top of the beautiful Astore Valley, with a light cover of oak trees and other greenery. There is not much greenery (as of 2013) due to illegal loging of the forest by locals and timber mafia. The region has low average rainfall and low vegetation cover hence the loss of forest cover is of a very serious concern.") )
            ceoArray.append(ceoObject(username:"SHEOSER LAKE", profilePicture: UIImage(named: "sheoser lake")!, post: "Sheosar Lake is a lake situated in Deosai National Park, in Gilgit-Baltistan province of northern Pakistan.The lake is at an elevation of 4,142 metres (13,589 ft) in the Karakoram-West Tibetan Plateau alpine steppe. Its approximate length is 2.3 kilometres (1.4 mi), width 1.8 kilometres (1.1 mi), and average depth is 40 metres") )
            ceoArray.append(ceoObject(username:"SHIGAR VALLEY", profilePicture: UIImage(named: "shigar valley")!, post: "Shigar Valley is a valley in Baltistan in northern Pakistan that is watered by the Shigar River. The valley stretches about 170 km from Skardu to Askole and is the gateway to the high mountains of the Karakoram. The town of Shigar is the largest settlement in valley. Even though the Shigar Valley is a remote and largely inaccessible place, there are several villages in the valley. Askole is the last settlement in the Shigar Valley, which is still far from the high mountains. Shigar was formerly an administrative sub-division of Skardu District, but is now a district in its own right. The Ernst & Young future leaders in MENA under LEAP (Leadership Excellence Acceleration Programme) visited Shigar in September 2015 to help build and support the community with a single goal to put the beautiful people and town of Shigar onto the world map! The team included Zeeshan khwaja, Ata Malik, Alex Collins, Tamara Habra, Ahmad Hajjar & Phillipe Najjar.") )
            ceoArray.append(ceoObject(username:"SKARDU", profilePicture: UIImage(named:   "skardu")!, post: "Skardu is a town in Pakistan's Gilgit-Baltistan region and serves as the capital of Skardu District. Skardu is located in the 10 kilometres (6 miles) wide by 40 kilometres (25 miles) long Skardu Valley, at the confluence of the Indus and Shigar Rivers[1] at an altitude of nearly 2,500 metres (8,202 feet). The town is considered a gateway to the eight-thousanders of the nearby Karakoram Mountain range..[citation needed] The town is located on the Indus river, which separates the Karakoram Range from the Himalayas.") )
            ceoArray.append(ceoObject(username:"SATPARA LAKE", profilePicture: UIImage(named: "satpara lake")!, post: "Satpara Lake is a natural lake near Skardu, Gilgit-Baltistan, Pakistan, which supplies water to Skardu Valley. It is fed by the Satpara Stream. Satpara Lake is situated at an elevation of 2,636 meters (8,650 ft) above sea level and is spread over an area of 2.5 km≤. The completion of Satpara Dam downstream of the lake has enlarged the size of Satpara Lake.") )
            ceoArray.append(ceoObject(username:"SHANDUR TOP", profilePicture: UIImage(named: "shandur top")!, post: "Shandur Top (el. 12,200 feet (3,700 m)) located in Chitral District, Chitral-Gilgit-Baltistan, Pakistan. Shandur is often called the 'Roof of the World'. The top is flat, a plateau and can be crossed between late April and early November. The grade is very gradual, and the area is crossed by plentiful small streams during summer. The boundary line between Ghizer District and Chitral District is also situated in Shandur Top in Punji-Lasht as per the international boundary law division by watershed initially demarcated by Lt. Col AG Durand( also known as Durand boundary line). Every year there is a polo match played on Shandur Top between the teams of Chitral District and Ghizer District. Shandur Pass is one of the major mountain passes of Chitral-Gilgit-Baltistan.") )
            ceoArray.append(ceoObject(username:"RAKAPOSHI", profilePicture: UIImage(named: "rakaposhi")!, post: "Rakaposhi is a mountain in the Karakoram mountain range in Pakistan.[1] It is situated in the middle of Nagar Valley Nagar District and Danyore and Bagrote valley approximately 100 km north of the capital city Gilgit of the semi autonomous GilgitñBaltistan region of Pakistan. Rakaposhi means Snow Covered in the local language. Rakaposhi is also known as Dumani (Mother of Mist or Mother of Clouds). It is ranked 27th highest in the world and 12th highest in Pakistan, but it is more popular for its beauty than its rank might suggest.") )
            ceoArray.append(ceoObject(username:"SHIGAR FORT", profilePicture: UIImage(named: "shigar fort")!, post: "The Shigar Fort means The Fort on Rock[1] is an old fort of Baltistan and Pakistan located in the town of Shigar. It was built in the 17th century by the Raja of Amacha Dynasty of Shigar.The fort has been restored by Aga Khan Cultural Service Pakistan (AKCSP-P), the Pakistan arm of the Aga Khan Historic Cities Programme. After restoration, the Fort was converted to a museum and luxury hotel managed by Serena Hotels. The restoration process took place from 1999 to 2004 and cost approximately US$1.4 million.") )
            ceoArray.append(ceoObject(username:"SHANGRILA RESORT", profilePicture: UIImage(named: "shangrila resort")!, post: "Shangrila Resort (Lower Kachura Lake) is located in Kachura village 20 minutes from Skardu city (nearly 2,500 m or 8,200 feet) town. The lake is known as Shangrila lake after a resort built on its bank in 1983. It is a popular tourist destination, and has a unique restaurant that is built on the fuselage of an aircraft that had crashed nearby. Shangrila was established in 1983 with the opening of the first Resort Hotel in Skardu, Baltistan. Shangrila Resort Hotel was founded by the late Muhammad Aslam Khan, the first commander of the Northern Scouts of the Pakistan Army.") )
            ceoArray.append(ceoObject(username:"UPPER KACHURA LAKE", profilePicture: UIImage(named: "upper kachura lake")!, post: "Upper Kachura Lake is of clear water and has a depth of 70 metres (230 ft).In winter the surface is frozen solid. The upper Indus River flows nearby at a lower elevation.The beauty of the Upper Kachura Lake is almost untampered and mostly unexplored by travelers, due to lack of infrastructure owing to its rough terrain The area has a rich flora of the Western Himalayan subalpine conifer forests ecoregion, and also known for its wild apricot - Prunus armeniaca orchards. Recreation activities at Upper Kachura Lake include hiking, trout fishing, and Himalaya mountaineering.") )
            ceoArray.append(ceoObject(username:"SHIMSHAL", profilePicture: UIImage(named: "shimshal")!, post: "Shimshal is a village located in Gojal Tehsil of Hunza District, in the GilgitñBaltistan region of Pakistan formerly known as Northern Areas of Pakistan. It lies at an altitude of 3,100 m above sea level and is the highest settlement in Hunza Valley of Pakistan. It is the bordering village that connects Gilgit-Baltistan area of Pakistan with China. The total area of Shimshal is approximately 3,800 km2 and there are around two thousand inhabitants with a total of two hundred and forty households. Shimshal is made up of four major hamlets; Farmanabad, Aminabad, center Shimshal and Khizarabad. Farmanabad is a new settlement that comes first on reaching Shimshal") )
            ceoArray.append(ceoObject(username:"ASTORE", profilePicture: UIImage(named: "astore")!, post: "Astore Valley (el. 2,600 m (8,500 ft)) is located in Astore District in the Pakistani region of Gilgit-Baltistan. The valley, adjoining the eastern side of mountain Nanga Parbat, is about 120 km (75 mi) long, having area of 5,092 km2 (1,966 sq mi).The entrance of the valley is located about 60 km southeast of Gilgit with four side-valleys. The valley has more than 100 villages with a total population of 71,666 (Census 1998)[citation needed], including Gudai, Shekong, Dass Kariam, Loas, Louze, Chilm, Bubin, Gorikot, Parisheng Eid Ghah, Fina, Bulen, Chongra, Tari Shing, Rattu, Kamri, and Minimerg. Rama lake and pastures are the most famous tourist attraction in the region. The majority of people practice subsistence agriculture and livestock is the main source of livelihood complemented by seasonal work in down districts of the country. Due to its diverse landscape and climatic conditions the valley provides excellent habitat for a variety of commercially important medicinal plants.") )

            break;
            
            
        case "KASHMIR":
         
            ceoArray.append(ceoObject(username:"KEL", profilePicture: UIImage(named: "k1")!, post: "Kel is a village in Neelam Valley, Kashmir, Pakistan. It is located 155 kilometers from Muzaffarabad at the altitude of 6,879 feet.Buses run daily between Muzaffarabad and Kel in good weather. Few private hotels and a rest house of AJK Tourism and Archeology Department located there for tourists stay. It also has a bank, college, hospital and a bazaar.The Kel is located near Line of Control and the road which leads there is non metallic. There are frequent landslides during Summers, and Snow slides on this road during winters. In winters all the routes are blocked and it is very difficult to reach there. All these factors combined made it one of the most difficult places to reach.") )
            ceoArray.append(ceoObject(username: "MUZAFARABAD",profilePicture: UIImage(named: "m1")!, post: "Muzaffarabad is the capital of Azad Jammu and Kashmir, Pakistan.It is located in Muzaffarabad District on the banks of the Jhelum and Neelum rivers. The district is bounded by Khyber-Pakhtunkhwa in the west, by the Kupwara and Baramulla districts of Indian-administered territory of Jammu and Kashmir in the east, and the Neelum District of Azad Kashmir in the north.") )
            ceoArray.append(ceoObject(username: "SHARDAH",profilePicture: UIImage(named: "sh1")!, post: "Sharda is a small town in Neelam District in Azad Kashmir, Pakistan. It is one of the two tehsils of Neelum district, and is reputed to be the most beautiful spot of the Neelum valley. It is located on the banks of the Neelum river at an altitude of 1981m, about 136 kilometers Northeast of Muzaffarabad.") )
            ceoArray.append(ceoObject(username: "TAOBAT",profilePicture: UIImage(named: "t1")!, post: "Taobat is a village in Neelam Valley, Azad Kashmir, Pakistan. It is located 200 kilometers from Muzaffarabad and 39 kilometers from Kel. It is the last station in Neelam valley.It is also the nearest location from where Kishenganga river enters Pakistani territory and becomes River Neelum.Taobat is accessible from Kel by unmetalled road. A Motel of AJK Tourism and Archeology Department and a small number of hotels with meager resources are located there for tourists stay.") )
            ceoArray.append(ceoObject(username:"ARANG KEL", profilePicture: UIImage(named: "arang kel")!, post: "Arang Kel is a lush green village, hill station and tourist spot in Neelam valley, Azad Kashmir, Pakistan. It is located on the hill top above Kel at the altitude of 8,379 feet (2,554 m) feet.The village is accessible by a 2 kilometers (1.2 mi) trek from Kel. To reach Kel people usually enter into the Neelam valley from Muzafarabad. Roads are only good from Muzafarabad up to Athmuqam and one can use public van service to reach there. After passing Athmuqam, one has to use a personal or rented vehicle to pass through Keran, Kutton, Dawarrian and Sharda and then to reach Kel. Kel is located just 19 kilometers (12 mi) ahead from Sharda at the altitude of 6,879 feet (2,097 m).") )
            ceoArray.append(ceoObject(username:"JAGRAN", profilePicture: UIImage(named: "jagran")!, post: "Kutton( Also known as Jagran Valley ) is a village and tourist resort in Neelam Valley, Azad Kashmir, Pakistan.Kutton is accessible by Neelam road from Muzaffarabad branches off from Kundal Shahi.Rest houses of AJK Tourism and Archeology Department and Water and Power Development Authority (WAPDA) are located here. Some private rest houses and hotels are also available here for tourists stay.") )
            ceoArray.append(ceoObject(username:"CHITTA KATHA LAKE", profilePicture: UIImage(named: "chitta katha lake")!, post: "Chitta Katha Lake is located in Shounter valley, Azad Kashmir at the elevation of 13,500 feet (4,100 m). Chitta Katha means White Stream; it is the local name of the stream coming down from the Hari Parbat originating from the lake called Chitta Katha Sar or lake of the Mount Hari parbat. This Mountain is sacred for some people who relate it to Lord Shiva and consider it abode of the Lord and identify it as Kailash.It is located in Shontar valley of the Tehsil sharda of Neelum district of Pakistan administered Kashmir. Chita katha can be approached from kel to domel bala about 20 km through jeeps and then 5 km trekking by foot. The Chitta Katha Lake is a lake in Shonter valley in Azad Kashmir, Pakistan. It is located at an elevation of 4,100 meters (13,500 ft).") )
          
            
            ceoArray.append(ceoObject(username:"KASHMIR ABSHAR", profilePicture: UIImage(named: "kashmir abshaar")!, post: "Kashmir Abshaar is the waterfall located 5 Km before Muzaffarabad City. Visitors come there to see the beautiful view and have tea, cold drink & snack on Abshaar side restaurant.Waterfalls are common in Azad Kashmir, but this one is best amongst the all which I have seen so far. Those who are passing through or visiting Muzaaffarabad should must visit this place and stay at least for 3 to 4 hours.The excited Jehlum river is falling between the Muzaffarabad road and Kashmir Abshaar so you need to use the manual chair lift ( not runs on electricity) from road side which will take you to the other side of the river to reach this picnic point. The round trip charges for using the chair lift is Rs.50 per person.") )
            ceoArray.append(ceoObject(username:"RATTI GALI LAKE", profilePicture: UIImage(named: "Ratti Gali Lake")!, post: "The Ratti Gali Lake is an alpine glacial lake which is located in Neelum Valley, Pakistan Administered Kashmir at an altitude of 12,130 feet (3,700 m). The lake is fed by the surrounding glacier waters of the mountains.The lake is accessible from Dowarian by an unmetalled 19 kilometers (12 mi) road cum hiking trek through breath-taking sites. Dowarian is the base camp to this lake.[1] Jeeps are easily available from Dowarian & during peak season they will cost you around PKR 8,000. From Dawarian it takes almost Two and half hour to reach base camp at Domail. From that point it's preferable to get horses , as the tracking is too much steep. Young people can do tracking, it will take almost one hour to reach lake. All the tour is safe for families also. Take your rain coats and jackets along with you. Mr. Mustansar Hussain Tarar was the first person who explored this paradise cradled in the lap of majestic mountains & then wrote his all time favorite Travelogue Ratti Gali") )
            ceoArray.append(ceoObject(username:"NOORI TOP", profilePicture: UIImage(named: "noori top")!, post: "Noori Top is located on the border between NWFP and Kashmir. The long journey to Noori Top from Naran starts on the main Naran-Babusar jeep road (the road under renovation and re-carpeting). The road passes through the small towns of Batakundi, Burwai and Jalkad along the Kunhar River. There are a few shops and local hotels in these towns and as the tourist flow beyond Naran in minimal, these towns have escaped both the destruction and development that mass tourism brings in its wake.  Although the local mud and stone construction, unpolluted air and water and, thick forests and green hills are welcome contrast to the mad rush of tourists and concrete jungle at Naran, the lack of tourists have also resulted in minimum basic facilities for the local population, with no electricity, and minimum health and communication infrastructure.At Jalkad, the recently constructed jeep road to Noori Top branches off from the main road which continues towards Babusar Pass. The traffic on this narrow road is minimal, with few jeeps and old 4x4 trucks plying between Naran and Kashmir.") )
            break;
            
            
        default:
            print("")
        }
        collectionview.delegate = self
        collectionview.dataSource = self
        
        
        lblTitle.text = CityTitle
        
        // Do any additional setup after loading the view.
    }
    
 func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return ceoArray.count
    }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
    let cell = collectionview.dequeueReusableCell(withReuseIdentifier: "ceoCell", for: indexPath) as! galleryCollectionViewCell
        //cell.username.text = ceoArray[indexPath.item].username
        cell.imageview.image = ceoArray[indexPath.item].profilePicture
        cell.post.text = ceoArray[indexPath.item].post
        
        cell.button.setTitle(ceoArray[indexPath.item].username, for: .normal)
        cell.button.tag = indexPath.row
        cell.button.addTarget(self, action: #selector(self.btnClick(sender:)), for: .touchUpInside)
        
        
        return cell
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    
        
    }
    
    
    func btnClick(sender: AnyObject) {
        
        
        let btn = sender as! UIButton
        
        
        selectedCID = btn.tag
        
    
        self.performSegue(withIdentifier: "GotoCityDetail", sender: self)
        print("\(btn.tag)")
        
    }
    
    
    
    

    
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
        
        
        
        if segue.identifier == "GotoCityDetail" {
            
            
            let VCObj : thirdViewController = segue.destination as! thirdViewController
            
            
            VCObj.hotelName = ceoArray[selectedCID].username
            VCObj.hotelDesc = ceoArray[selectedCID].post
            VCObj.image = ceoArray[selectedCID].profilePicture
        }
        
        
        
        
        
    }


}
